### ISSUE TITLE
Inheriting from an not existing Fusion Object (misspelling)

### ISSUE THREAD

**Issue by vectoholic** [dimaip/Dimaip.TwitterHelper#3]
> The Fusion object `Neos.Neos:Template` which you tried to inherit from does not exist.

```
prototype(Dimaip.TwitterHelper:Tweet) < prototype(Neos.Neos:Template) {
	templatePath = 'resource://Dimaip.TwitterHelper/Private/Templates/Tweet.html'
	tweet = ${tweet}
}
```

**Comment by dimaip** [comment]
Hey @vectoholic!
Maybe you meant `Neos.Fusion:Template`?

**Comment by vectoholic** [comment]
Yes but in your code you wrote ```Neos.Neos:Template```in Root.fusion at line 14. I discovered it in your Package by upgrading a Project to Neos 3.2.

https://github.com/dimaip/Dimaip.TwitterHelper/blob/529b86570b896879e985040113d502713341878a/Resources/Private/Fusion/Root.fusion#L14

**Comment by dimaip** [comment]
Oh, sorry, misunderstood you. Fixed.

**Comment by vectoholic** [comment]
Thx but can you make an release from the master so I can you it in my project ;-)

**Comment by dimaip** [comment]
Done!

**Comment by vectoholic** [comment]
Thx for the quick fix! Appreciate it!
