### ISSUE TITLE
Wrong Namespace Name

### ISSUE THREAD

**Issue by beardcoder** [dimaip/Dimaip.TwitterHelper#6]
This must be end with 2 "/"

"Dimaip\\TwitterHelper\\": "Classes/"

https://github.com/dimaip/Dimaip.TwitterHelper/blob/828a50b1ee8481ea69ce4a02ae34b0fadf8e94b5/composer.json#L12

**Comment by dimaip** [comment]
Does it? Seems to work as is. But fill free to submit a PR if you like the other syntax better.
